
import java.io.FileNotFoundException;
import java.util.logging.Level;
import java.util.logging.Logger;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author rohit
 */
public class levelsmis extends javax.swing.JFrame {

    /**
    
     */
    public levelsmis() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lm1 = new javax.swing.JButton();
        lm2 = new javax.swing.JButton();
        lm3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lm1.setText("Level1");
        lm1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lm1ActionPerformed(evt);
            }
        });

        lm2.setText("Level2");
        lm2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lm2ActionPerformed(evt);
            }
        });

        lm3.setText("Level3");
        lm3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lm3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(132, 132, 132)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lm3)
                    .addComponent(lm2)
                    .addComponent(lm1))
                .addContainerGap(196, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(lm1)
                .addGap(50, 50, 50)
                .addComponent(lm2)
                .addGap(60, 60, 60)
                .addComponent(lm3)
                .addContainerGap(90, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lm1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lm1ActionPerformed
        // TODO add your handling code here:misspelt mis = new misspelt();
         
       misspelt mis = new misspelt();
       int level=1;
        mis.setVisible(true);
        try {
            mis.call(level);
        } catch (FileNotFoundException ex) {
            Logger.getLogger(menuform.class.getName()).log(Level.SEVERE, null, ex);
        }
        this.dispose();
    }//GEN-LAST:event_lm1ActionPerformed

    private void lm2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lm2ActionPerformed
        // TODO add your handling code here:
         
       misspelt mis = new misspelt();
       int level=2;
        mis.setVisible(true);
        try {
            mis.call(level);
        } catch (FileNotFoundException ex) {
            Logger.getLogger(menuform.class.getName()).log(Level.SEVERE, null, ex);
        }
        this.dispose();
    }//GEN-LAST:event_lm2ActionPerformed

    private void lm3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lm3ActionPerformed
        // TODO add your handling code here:
         
       misspelt mis = new misspelt();
       int level=3;
        mis.setVisible(true);
        try {
            mis.call(level);
        } catch (FileNotFoundException ex) {
            Logger.getLogger(menuform.class.getName()).log(Level.SEVERE, null, ex);
        }
        this.dispose();
    }//GEN-LAST:event_lm3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(levelsmis.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(levelsmis.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(levelsmis.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(levelsmis.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new levelsmis().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton lm1;
    private javax.swing.JButton lm2;
    private javax.swing.JButton lm3;
    // End of variables declaration//GEN-END:variables
}
