
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.io.File;
import java.io.FileNotFoundException;
import java.util.Arrays;
import java.util.Scanner;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.util.prefs.Preferences;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.Timer;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author SAI
 */
public class misspelt extends javax.swing.JFrame {

    /**
     * Creates new form 
     */
    int i=0,j,total=0;
    Scanner sc; 
     int k;
     String[] cw;
     String[] ww;
     int n;
     String gs;
    Scanner scan; 
    int score=0;
    int cnt=180;
    String st="";
    public misspelt() {
         ActionListener actListner;
        
         
        actListner = new ActionListener() {
            
            @Override
            
            public void actionPerformed(ActionEvent event) {
                
               
                clk.setText("remaining secs : "+cnt);
                //System.out.println(cnt);
                cnt=cnt-1;
                
                if(cnt==0)
                {
                    ((Timer)event.getSource()).stop();
                   
                   // JOptionPane.showMessageDialog(,"Time up", "MSG",JOptionPane.PLAIN_MESSAGE);
                    JOptionPane.showMessageDialog(clk, "Time Up");
                    JOptionPane.showMessageDialog(clk, "Your Final score is "+score+" out of "+total);
                
              
                     new menuform("user").setVisible(true);
         
                    
                }
            }
            
        };
  Timer timer = new Timer(1000, actListner);


  timer.start();
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        ta = new javax.swing.JTextArea();
        clk = new javax.swing.JLabel();
        text1 = new javax.swing.JLabel();
        b2 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        word = new javax.swing.JTextField();
        c = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        num = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        ta.setEditable(false);
        ta.setColumns(20);
        ta.setRows(20);
        jScrollPane1.setViewportView(ta);

        clk.setText("remaining secs :");

        text1.setText("Your score is  0");

        b2.setText("Exit");
        b2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b2ActionPerformed(evt);
            }
        });

        jLabel3.setText("Enter a word");

        c.setText("submit");
        c.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cActionPerformed(evt);
            }
        });

        jLabel1.setText("Enter number");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(61, 61, 61)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(c)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(word, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(clk, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(219, 219, 219))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(num, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(b2)
                                        .addGap(136, 136, 136)
                                        .addComponent(text1, javax.swing.GroupLayout.PREFERRED_SIZE, 301, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(26, 26, 26))))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(clk, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(text1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(19, 19, 19))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(word, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1)
                            .addComponent(num, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(c)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                        .addComponent(b2))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void b2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b2ActionPerformed
        // TODO add your handling code here:
         JOptionPane.showMessageDialog(this,"your score is "+score+" out of "+total ,"MSG", JOptionPane.PLAIN_MESSAGE);
          Preferences userPrefs = Preferences.userRoot().node("sample");
         String retrievedValue = userPrefs.get("user", "default_value_if_not_found");
         userPrefs.putInt(retrievedValue, score);
         int le,ti;
         if(score<10)
         {
             le=1;
         }
         else if(score>10 && score<20)
         {
             le=2;
         }
         else
         {
             le=3;
         }
         
            if(score*7>=(180-cnt))
         {
             ti=3;
         }
         
             else if(score*9>=(180-cnt))
             {
                 ti=2;
             }
         else
             {
                 ti=1;
             }
         userPrefs.putInt("mis", le);
         userPrefs.putInt("misti", ti);
         userPrefs.putInt("mist",cnt);
       
         try {
             
             Thread.sleep(1000);
             
         } catch (InterruptedException ex) {
             Logger.getLogger(vowelsform1.class.getName()).log(Level.SEVERE, null, ex);
         }
        
          new menuform("user").setVisible(true);
          this.dispose();
       
    }//GEN-LAST:event_b2ActionPerformed

    private void cActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cActionPerformed
        // TODO add your handling code here:
        
       
      
        if(num.getText().equals("") || word.getText().equals(""))
        {
            JOptionPane.showMessageDialog(this,"Enter both number and word" ,"MSG", JOptionPane.PLAIN_MESSAGE);
            
        }
       
        else{
              n=Integer.parseInt(num.getText());
        k=n;
        
        
        String s=word.getText();
        
        
        try
        {
        if(s.equals(cw[k-1]))
{
ww[k-1]=ww[k-1].replace(ww[k-1]," ");
score++;
text1.setText("Your score is "+score+" out of "+total);
num.setText("");
word.setText("");
//t.setText("");
}
else
        {
            JOptionPane.showMessageDialog(this,"You Entered Wrong Spelling" ,"MSG", JOptionPane.PLAIN_MESSAGE);
        }
 for(i=0;i<ww.length;i++)
{
    if(!ww[i].equals(" "))
    {
st=st+((i+1)+". "+ww[i]);
st=st+'\n';
}     
}
 ta.setText(st);
 st="";
        }catch(Exception e)
        {
           JOptionPane.showMessageDialog(this,"Enter Coresponding number" ,"MSG", JOptionPane.PLAIN_MESSAGE);
        }
        }
        
        
    }//GEN-LAST:event_cActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(misspelt.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(misspelt.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(misspelt.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(misspelt.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new misspelt().setVisible(true);
            }
        });
    }

    public void call(int level) throws FileNotFoundException
    {
        
    File file1 = 
      new File("d:\\java\\cwords.txt"); 
    Preferences userPrefs = Preferences.userRoot().node("sample");
         String retrievedValue = userPrefs.get("user", "default_value_if_not_found");
    
        try {
            sc = new Scanner(file1);
        } catch (FileNotFoundException ex) {
            Logger.getLogger(misspelt.class.getName()).log(Level.SEVERE, null, ex);
        }
  String str1 = new String();
    while (sc.hasNextLine()) 
     {
      str1=str1+sc.next();
      str1=str1+" ";
} 
 cw=str1.split(" ");
 File file2 = 
      new File("d:\\java\\wwords.txt"); 
    
        try {
            scan = new Scanner(file2);
        } catch (FileNotFoundException ex) {
            Logger.getLogger(misspelt.class.getName()).log(Level.SEVERE, null, ex);
        }
  String str2 = new String();
    while (scan.hasNextLine()) 
     {
      str2=str2+scan.next();
      str2=str2+" ";
} 
 ww=str2.split(" ");
for(int k=0;k<cw.length;k++)
{
if(!cw[k].equals(ww[k]))
total++;
}
for(i=0;i<ww.length;i++)
{
st=st+((i+1)+". "+ww[i]);
st=st+'\n';
}
ta.setText(st);
st="";
 }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton b2;
    private javax.swing.JButton c;
    private javax.swing.JLabel clk;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField num;
    private javax.swing.JTextArea ta;
    private javax.swing.JLabel text1;
    private javax.swing.JTextField word;
    // End of variables declaration//GEN-END:variables
}
